[tool.flake8]
max-line-length = 99
exclude = [ "*/migrations/*", "settings_local.py", "settings.py", "manage.py" ]

[tool.black]
skip-string-normalization = true
line-length = 99
target-version = ['py312']
force-exclude = '\b(static/|docker/|apps_static/|nginx/|.git/|.vscode/|.conda/|.venv/|templates/|_dev/|fixtures/|migrations/|manage.py)'

[tool.isort]
profile = "black"
src_paths = ["."]
line_length = 99
skip = [ "manage.py" ]
skip_glob = [ "*/migrations/*", ".venv/*", ".conda/*", ".git/*", ".github/*", ".vscode/*", ".pytest_cache/*", "*/__pycache__/*", "*/.mypy_cache/*", ".idea/*" ]
combine_star = true
order_by_type = true
force_single_line = true
known_first_party = ["apps"]
known_django = "django"
sections = [ "FUTURE", "STDLIB", "DJANGO", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER" ]
import_heading_stdlib = "Standard Library"
import_heading_thirdparty = "3rd-Party"
import_heading_firstparty = "Project"
import_heading_localfolder = "Local"
import_heading_django = "Django"


[tool.pyink]
line-length = 99
pyink-use-majority-quotes = true
pyink-indentation = 4
force-exclude = '\b(static/|docker/|apps_static/|nginx/|venv/|templates/|_dev/|fixtures/|migrations/|manage.py)'

[tool.djlint]
profile = "django"
ignore = "H014"
close_void_tags = true
max-line-length = 99
blank_line_after_tag = "load,extends"
format_css = true
format_js = true
indent = 2

[tool.djlint.css]
indent_size = 2

[tool.djlint.js]
indent_size = 2

[tool.coverage.run]
relative_files = true
omit = [ "manage.py", "apps/*/migrations/*.py" ]
